import { getUserSession } from '@/lib/auth';
import './globals.css';

import { AppLayout } from '@/components/layout/AppLayout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const session = await getUserSession();
  return (
    <html lang="en">
      <body>
        <AppLayout userSession={session}>{props.children}</AppLayout>
      </body>
    </html>
  );
}
